api:
    entity_aliases:
        Extend\Entity\EV_Acc_Internal_Rating:
            alias:        customerrating
            plural_alias: customerratings

        Oro\Bundle\CustomerBundle\Api\Model\Contact:
            alias: suggestcustomer
            plural_alias: suggestcustomer

        Oro\Bundle\CustomerBundle\Api\Model\SearchByPhone:
            alias: searchcustomerbyphone
            plural_alias: searchcustomerbyphone
            
    entities:
        Oro\Bundle\CustomerBundle\Entity\Customer:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer.md'
            fields:
                dataChannel:
                    exclude: true
                linkCustomerOrganization:
                    exclude: false 
            filters:
                fields:
                    name:
                        operators: ['=', '!=', '*', '!*', '~', '!~', '^', '!^', '$', '!$']
                    phone: 
                        operators: ['=', '!=', '*', '!*', '~', '!~', '^', '!^', '$', '!$']
                    countryCode:
                        operators: ['=', '!=', '*', '!*', '~', '!~', '^', '!^', '$', '!$']        
            subresources:
                addresses:
                    actions:
                        update_relationship: false
                        add_relationship: false
                        delete_relationship: false

        Extend\Entity\EV_Acc_Internal_Rating:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer.md'

        Oro\Bundle\CustomerBundle\Entity\CustomerGroup:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer_group.md'

        Oro\Bundle\CustomerBundle\Entity\CustomerUserRole:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer_user_role.md'

        Oro\Bundle\CustomerBundle\Entity\CustomerUser:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer_user.md'
            fields:
                emailLowercase:
                    exclude: true
                passwordChangedAt:
                    form_options:
                        mapped: false
                passwordRequestedAt:
                    form_options:
                        mapped: false
                loginCount:
                    form_options:
                        mapped: false
                lastLogin:
                    form_options:
                        mapped: false
            actions:
                create:
                    fields:
                        password:
                            exclude: false # set manually because this field is excluded globally
                            form_options:
                                property_path: plainPassword
            subresources:
                addresses:
                    actions:
                        update_relationship: false
                        add_relationship: false
                        delete_relationship: false

        Oro\Bundle\CustomerBundle\Entity\CustomerAddress:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer_address.md'
            fields:
                createdAt:
                    property_path: created
                updatedAt:
                    property_path: updated
                customRegion:
                    exclude: false # set manually because this field is marked as excluded in entity.yml
                    property_path: regionText
                customer:
                    property_path: frontendOwner
                    form_options:
                        constraints:
                            - NotBlank: ~
                types:
                    data_type: array
                    max_results: -1
                    exclusion_policy: all
                    fields:
                        default:
                            form_type: Oro\Bundle\ApiBundle\Form\Type\BooleanType
                            form_options:
                                required: true
                        addressType:
                            property_path: type.name
                            form_type: Oro\Bundle\AddressBundle\Api\Form\Type\AddressTypeType
                            form_options:
                                required: true
                                property_path: type
                    form_options:
                        property_path: addressTypes
                systemOrganization:
                    form_options:
                        mapped: false
            filters:
                fields:
                    country:
                        allow_array: true
                    region:
                        allow_array: true
                    addressType:
                        description: Filter records by address type, e.g. shipping, billing, etc.
                        data_type: string
                        property_path: types.type
                        allow_array: true
            actions:
                update:
                    fields:
                        customer:
                            form_options:
                                mapped: false
            subresources:
                systemOrganization:
                    actions:
                        update_relationship: false
                customer:
                    actions:
                        update_relationship: false
                country:
                    actions:
                        update_relationship: false
                region:
                    actions:
                        update_relationship: false

        Oro\Bundle\CustomerBundle\Entity\CustomerAddressToAddressType:
            # this entity does not have own API resource,
            # but it should be defined to correct work of "types" property
            # of the customer address API resource
            actions: false
        Oro\Bundle\CustomerBundle\Entity\CusDemo:
            # this entity does not have own API resource,
            # but it should be defined to correct work of "types" property
            # of the customer address API resource
            actions: true

        Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer_user_address.md'
            fields:
                createdAt:
                    property_path: created
                updatedAt:
                    property_path: updated
                customRegion:
                    exclude: false # set manually because this field is marked as excluded in entity.yml
                    property_path: regionText
                customerUser:
                    property_path: frontendOwner
                    form_options:
                        constraints:
                            - NotBlank: ~
                types:
                    data_type: array
                    max_results: -1
                    exclusion_policy: all
                    fields:
                        default:
                            form_type: Oro\Bundle\ApiBundle\Form\Type\BooleanType
                            form_options:
                                required: true
                        addressType:
                            property_path: type.name
                            form_type: Oro\Bundle\AddressBundle\Api\Form\Type\AddressTypeType
                            form_options:
                                required: true
                                property_path: type
                    form_options:
                        property_path: addressTypes
                systemOrganization:
                    form_options:
                        mapped: false
            filters:
                fields:
                    country:
                        allow_array: true
                    region:
                        allow_array: true
                    addressType:
                        description: Filter records by address type, e.g. shipping, billing, etc.
                        data_type: string
                        property_path: types.type
                        allow_array: true
            actions:
                update:
                    fields:
                        customerUser:
                            form_options:
                                mapped: false
            subresources:
                systemOrganization:
                    actions:
                        update_relationship: false
                customerUser:
                    actions:
                        update_relationship: false
                country:
                    actions:
                        update_relationship: false
                region:
                    actions:
                        update_relationship: false

        Oro\Bundle\CustomerBundle\Entity\CustomerUserAddressToAddressType:
            # this entity does not have own API resource,
            # but it should be defined to correct work of "types" property
            # of the customer user address API resource
            actions: false

        Oro\Bundle\CustomerBundle\Entity\LinkCustomerOrganization:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api_frontend/link_customer_organization.md'
            actions: true

        Oro\Bundle\CustomerBundle\Api\Model\SearchByPhone:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/search_customer_byphone.md'
            fields:
                phone:
                    data_type: string
                countryCode:
                    data_type: string
                data:
                    data_type: array
            actions:
                get: false
                get_list: false
                create:
                    description: Get API Access Key
                    fields:
                        phone:
                            direction: input-only
                        countryCode:
                            direction: input-only
                        data:
                            direction: output-only
                    status_codes:
                        201: false
                        200: Returned when the credentials are valid and API access key exists
                        403: Returned when the credentials are not valid or API access key does not exist
                        409: false

        Oro\Bundle\CustomerBundle\Api\Model\Contact:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/suggest_customers.md'
            fields:
                lstPhone:
                    data_type: string
                data:
                    data_type: array
            actions:
                get: false
                get_list: false
                create:
                    description: Get API Access Key
                    fields:
                        lstPhone:
                            direction: input-only
                        data:
                            direction: output-only
                    status_codes:
                        201: false
                        200: Returned when the credentials are valid and API access key exists
                        403: Returned when the credentials are not valid or API access key does not exist
                        409: false
