api:
    entity_aliases:
        Oro\Bundle\CustomerBundle\Api\Model\Login:
            alias: login
            plural_alias: login
        # Oro\Bundle\CustomerBundle\Api\Model\Contact:
        #     alias: lstphone
        #     plural_alias: lstphone
    entities:
        # Oro\Bundle\CustomerBundle\Api\Model\Contact:
        #     # documentation_resource: '@OroCustomerBundle/Resources/doc/api_frontend/login.md'
        #     fields:
        #         lstPhone:
        #             data_type: string
        #         output:
        #             data_type: array
        #     actions:
        #         create:
        #             description: Get API Access Key
        #             fields:
        #                 lstPhone:
        #                     direction: input-only
        #                 output:
        #                     direction: output-only
        #             status_codes:
        #                 201: false
        #                 200: Returned when the credentials are valid and API access key exists
        #                 403: Returned when the credentials are not valid or API access key does not exist
        #                 409: false

        Oro\Bundle\CustomerBundle\Api\Model\Login:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api_frontend/login.md'
            fields:
                username:
                    data_type: string
                password:
                    data_type: string
                apiKey:
                    data_type: string
                customerId:
                    data_type: string
                customerUserId:
                    data_type: string
            actions:
                get: false
                get_list: false
                update: false
                delete: false
                delete_list: false
                create:
                    description: Get API Access Key
                    fields:
                        username:
                            direction: input-only
                            form_options:
                                constraints:
                                    - NotBlank: ~
                        password:
                            direction: input-only
                            form_type: Symfony\Component\Form\Extension\Core\Type\PasswordType
                            form_options:
                                constraints:
                                    - NotBlank: ~
                        apiKey:
                            direction: output-only
                            
                        customerId:
                            direction: output-only

                        customerUserId:
                            direction: output-only
                    status_codes:
                        201: false
                        200: Returned when the credentials are valid and API access key exists
                        403: Returned when the credentials are not valid or API access key does not exist
                        409: false

  

        Oro\Bundle\CustomerBundle\Entity\CustomerGroup:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api_frontend/customer_group.md'
            actions:
                create: false
                update: false
                delete: false
                delete_list: false

        Oro\Bundle\CustomerBundle\Entity\CustomerUserRole:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api_frontend/customer_user_role.md'
            fields:
                public:
                    exclude: true
                selfManaged:
                    exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false


        Oro\Bundle\CustomerBundle\Entity\CustomerUser:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api_frontend/customer_user.md'
            fields:
                emailLowercase:
                    exclude: true
                passwordChangedAt:
                    form_options:
                        mapped: false
                passwordRequestedAt:
                    form_options:
                        mapped: false
                loginCount:
                    form_options:
                        mapped: false
                lastLogin:
                    form_options:
                        mapped: false
              


            filters:
                fields:
                    phone: 
                        operators: [ '=' ]
                        
            actions:
                create:
                    fields:
                        password:
                            exclude: false # set manually because this field is excluded globally
                            form_options:
                                property_path: plainPassword
                update:
                    fields:
                        password:
                            exclude: false # set manually because this field is excluded globally
                            form_options:
                                property_path: plainPassword

            subresources:
                addresses:
                    actions:
                        update_relationship: false
                        add_relationship: false
                        delete_relationship: false

        Oro\Bundle\CustomerBundle\Entity\CustomerAddress:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api_frontend/customer_address.md'
            fields:
                createdAt:
                    property_path: created
                updatedAt:
                    property_path: updated
                customRegion:
                    exclude: false # set manually because this field is marked as excluded in entity.yml
                    property_path: regionText
                customer:
                    property_path: frontendOwner
                    form_options:
                        constraints:
                            - NotBlank: ~
                types:
                    data_type: array
                    max_results: -1
                    exclusion_policy: all
                    fields:
                        default:
                            form_type: Oro\Bundle\ApiBundle\Form\Type\BooleanType
                            form_options:
                                required: true
                        addressType:
                            property_path: type.name
                            form_type: Oro\Bundle\AddressBundle\Api\Form\Type\AddressTypeType
                            form_options:
                                required: true
                                property_path: type
                    form_options:
                        property_path: addressTypes
            filters:
                fields:
                    country:
                        allow_array: true
                    region:
                        allow_array: true
                    addressType:
                        description: Filter records by address type, e.g. shipping, billing, etc.
                        data_type: string
                        property_path: types.type
                        allow_array: true
            actions:
                create: true
                update:
                    fields:
                        customer:
                            form_options:
                                mapped: false
            subresources:
                customer:
                    actions:
                        update_relationship: false
                country:
                    actions:
                        update_relationship: false
                region:
                    actions:
                        update_relationship: false

        Oro\Bundle\CustomerBundle\Entity\CustomerAddressToAddressType:
            # this entity does not have own API resource,
            # but it should be defined to correct work of "types" property
            # of the customer address API resource
            actions: false

        Oro\Bundle\CustomerBundle\Entity\CustomerTest:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api_frontend/customer_test.md'
            # this entity does not have own API resource,
            # but it should be defined to correct work of "types" property
            # of the customer address API resource
            actions: true            

        Oro\Bundle\CustomerBundle\Entity\LinkCustomerOrganization:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api_frontend/link_customer_organization.md'
            # this entity does not have own API resource,
            # but it should be defined to correct work of "types" property
            # of the customer address API resource
            
            fields:
                customer:
                    form_options:
                        mapped: true

            
        Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress:
            # documentation_resource: '@OroCustomerBundle/Resources/doc/api_frontend/customer_user_address.md'
            fields:
                createdAt:
                    property_path: created
                updatedAt:
                    property_path: updated
                customRegion:
                    exclude: false # set manually because this field is marked as excluded in entity.yml
                    property_path: regionText
                customerUser:
                    property_path: frontendOwner
                types:
                    data_type: array
                    max_results: -1
                    exclusion_policy: all
                    fields:
                        default:
                            form_type: Oro\Bundle\ApiBundle\Form\Type\BooleanType
                            form_options:
                                required: true
                        addressType:
                            property_path: type.name
                            form_type: Oro\Bundle\AddressBundle\Api\Form\Type\AddressTypeType
                            form_options:
                                required: true
                                property_path: type
                    form_options:
                        property_path: addressTypes
            filters:
                fields:
                    country:
                        allow_array: true
                    region:
                        allow_array: true
                    addressType:
                        description: Filter records by address type, e.g. shipping, billing, etc.
                        data_type: string
                        property_path: types.type
                        allow_array: true
            actions:
                update:
                    fields:
                        customerUser:
                            form_options:
                                mapped: false
            subresources:
                customerUser:
                    actions:
                        update_relationship: false
                country:
                    actions:
                        update_relationship: false
                region:
                    actions:
                        update_relationship: false

        Oro\Bundle\CustomerBundle\Entity\CustomerUserAddressToAddressType:
            # this entity does not have own API resource,
            # but it should be defined to correct work of "types" property
            # of the customer user address API resource
            actions: true

        Oro\Bundle\CustomerBundle\Entity\Customer:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer.md'
            fields:
                dataChannel:
                    exclude: true
                linkCustomersOrganizations:
                    exclude: true
            filters:
                fields:
                    createdAt:
                        exclude: false
                    updatedAt:
                        exclude: false
            subresources:
                addresses:
                    actions:
                        update_relationship: false
                        add_relationship: false
                        delete_relationship: false

                